portfolio/.NET/RecipeRecommand/Models/ErrorViewModel.cs
namespace RecipeRecommand.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

portfolio/.NET/RecipeRecommand/Models/Ingredient.cs
using RecipeRecommand.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace RecipeRecommand.Models
{
    public class Ingredient : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Image URL")]
        public string ImageURL { get; set; }

        // Relationships
        public virtual ICollection<Ingredient_Recipe> Ingredients_Recipes { get; set; }
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}

portfolio/.NET/RecipeRecommand/Models/Ingredient_Recipe.cs
namespace RecipeRecommand.Models
{
    public class Ingredient_Recipe
    {
        public int RecipeId { get; set; }
        public int IngredientId { get; set; }

        public virtual Recipe Recipe { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}

portfolio/.NET/RecipeRecommand/Models/Recipe.cs
using RecipeRecommand.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace RecipeRecommand.Models
{
    public class Recipe : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }

        // Relationships
        public virtual ICollection<Ingredient_Recipe> Ingredients_Recipes { get; set; }
        public virtual ICollection<Ingredient> Ingredient { get; set; }
    }
}

portfolio/.NET/RecipeRecommand/Controllers/IngredientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeRecommand.Data;
using RecipeRecommand.Data.Services;

namespace RecipeRecommand.Controllers
{
    public class IngredientsController : Controller
    {
        private readonly IIngredientsService _service;

        public IngredientsController(IIngredientsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allIngredients = await _service.GetAllAsync(n => n.Ingredients_Recipes);
            return View(allIngredients);
        }
    }
}

portfolio/.NET/RecipeRecommand/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeRecommand.Data;
using RecipeRecommand.Data.Services;
using RecipeRecommand.Data.Base;
using RecipeRecommand.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RecipeRecommand.Controllers
{
    public class RecipesController : Controller
    {
        private readonly IRecipesService _service;

        public RecipesController(IRecipesService service)
        {
            _service = service;
        }

        // Index show all recipes
        public async Task<IActionResult> Index()
        {
            var allRecipes = await _service.GetAllAsync(n => n.Ingredients_Recipes);
            return View(allRecipes);
        }

        // Search bar function
        public async Task<IActionResult> Filter(string searchString)
        {
            var allRecipes = await _service.GetAllAsync(n => n.Ingredients_Recipes);

            if (!string.IsNullOrEmpty(searchString))
            {
                // Exact search
                var filteredResult = allRecipes.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();
                // Keyword search but not yet implemented
                //var filteredResult = _service.Ingredients.Include(n => n.Name);
                return View("Index", filteredResult);
            }

            return View("Index", allRecipes);
        }

        // Get detail of recipe
        public async Task<IActionResult> Details(int id)
        {
            var recipeDetail = await _service.GetRecipeByIdAsync(id);
            return View(recipeDetail);
        }

        // Create recipe by user; not yet implemented
        //public async Task<IActionResult> Create()

        // Edit recipe by user
        public async Task<IActionResult> Edit(int id)
        {
            var recipeDetails = await _service.GetRecipeByIdAsync(id);
            if (recipeDetails == null) return View("NotFound");

            var response = new NewRecipeVM()
            {
                Id = recipeDetails.Id,
                Name = recipeDetails.Name,
                Description = recipeDetails.Description,
                ImageURL = recipeDetails.ImageURL,
                IngredientIds = recipeDetails.Ingredients_Recipes.Select(n => n.IngredientId).ToList(),
            };

            var recipeDropdownsData = await _service.GetNewRecipeDropdownsValues();
            ViewBag.Ingredients = new SelectList(recipeDropdownsData.Ingredients, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewRecipeVM recipe)
        {
            if (id != recipe.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var recipeDropdownsData = await _service.GetNewRecipeDropdownsValues();

                ViewBag.Actors = new SelectList(recipeDropdownsData.Ingredients, "Id", "Name");

                return View(recipe);
            }

            await _service.UpdateRecipeAsync(recipe);
            return RedirectToAction(nameof(Index));
        }
    }
}

portfolio/.NET/RecipeRecommand/Views/Ingredients/Index.cshtml
@model IEnumerable<Ingredient>

@{
	ViewData["Title"] = "List of Ingredients";
}

<div class="row">
	<div class="col-md-8 offset-md-2">

		<table class="table">
			<thead>
				<tr>
					<th>@Html.DisplayNameFor(model => model.ImageURL)</th>
					<th>@Html.DisplayNameFor(model => model.Name)</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded-circle" src="@item.ImageURL" alt="@item.Name" style="max-width: 150px"/>
						</td>
						<td class="align-middle">
							@Html.DisplayFor(modelItem => item.Name)
						</td>
						<td class="align-middle">
							<a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Edit </a>
							<a class="btn btn-outline-info"><i class="bi bi-eye"></i>Details </a>
							<a class="btn btn-danger text-white"><i class="bi bi-trash"></i>Delete </a>
						</td>
					</tr>
				}
			</tbody>
			
		</table>

	</div>
</div>

portfolio/.NET/RecipeRecommand/Views/Recipes/Details.cshtml
@model Recipe

@{
    ViewData["Title"] = "Recipe details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>

                        <p class="card-text">
                            <b>Ingredients: </b>
                            <hr />
                            @*<div class="row">
                                @foreach (var ingredient in Model.Ingredients_Recipes)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@ingredient.Ingredient.ImageURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Ingredients" asp-action="Details" asp-route-id="@ingredient.IngredientId">(@ingredient.Ingredient.Name)</a>
                                    </div>
                                }
                            </div>*@
                        </p>
                        <p class="card-text">
                            <b>Steps: </b>
                            <hr />
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

portfolio/.NET/RecipeRecommand/Views/Recipes/Edit.cshtml
@model NewRecipeVM
@using RecipeRecommand.Data;
 
@{
    ViewData["Title"] = "Update recipe";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update recipe</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="IngredientIds" class="control-label"></label>
                                <select asp-for="IngredientIds" class="form-control"  asp-items="ViewBag.Ingredients" multiple></select>
                                <span asp-validation-for="IngredientIds" class="text-danger"></span>
                            </div>  
                        </div>
                    </div>



                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageURL").val();
        });
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

portfolio/.NET/RecipeRecommand/Views/Recipes/Index.cshtml
@model IEnumerable<Recipe>

@{
	ViewData["Title"] = "List of Recipes";
}


<div class="row">
	@foreach (var item in Model)
	{
		<div class="col-md-4 col-xs-6 border-primary mb-3">
			<div class="card mb-3" style="max-width: 540px;">
				<div class="row g-0">
					<div class="col-md-12">
						<div class="card-header text-white bg-dark">
							<p class="card-text">
								<h5 class="card-title">
									@item.Name
								</h5>
							</p>
						</div>
					</div>
					<div class="col-md-6">
						<img src="@item.ImageURL" width="100%" alt="@item.Name">
					</div>
					<div class="col-md-6">
						<div class="card-body">
							<p class="card-text" id="description">@item.Description</p>
						</div>
					</div>
					<div class="col-md-12">
						<div class="card-footer ">
							<p class="card-text">
								<a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
									<i class="bi bi-eye-fill"></i> Show Details
								</a>
								<a class="btn btn-outline-info float-right" asp-action="Edit" asp-route-id="@item.Id">
									<i class="bi bi-pencil-squarel"></i> Edit
								</a>
								<a class="btn btn-danger text-white float-right" asp-action="Delete" asp-route-id="@item.Id">
									<i class="bi bi-trash"></i> Delete
								</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	}
</div>

<style type="text/css">
#description {
	line-height: 1.5em;
	height: 6em;
	overflow: hidden;
	width: 100%;
	font-family: Arial, sans-serif;
}
</style>

portfolio/.NET/RecipeRecommand/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipeRecommand</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipeRecommand.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Recipes" asp-action="Index">RecipeSearch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Ingredient Search
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Ingredients" asp-action="Index"> <i class="bi bi-camera-reels"></i> Ingredients</a>
                            </div>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Recipes" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a recipe..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" ><i class="bi bi-search"></i></button>
                    </form>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RecipeRecommand - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>